### PR TITLE
Fix for DbxRefreshResult Expires In

### LINKED ISSUE #304: DbxClientV2.refreshAccessToken() returns incorrect DbxRefreshResult.getExpiresAt()
SDK version: 3.1.5

 ```@Override
        public DbxRefreshResult refreshAccessToken() throws DbxException {
            credential.refresh(this.getRequestConfig());
            return new DbxRefreshResult(credential.getAccessToken(), credential.getExpiresAt());
        }
```

this method pass the expiresAt to expiresIn. And when DbxRefreshResult.getExpiresAt() it calculate by "issueTime + expiresIn * 1000;" However, the value of expiresIn is incorrect now.

### PR DESCRIPTION
**Pull request by rallat**
This change resolves #304 #294 
This change replaces in all the DbxClient implementors the `refreshAccessToken` function to make sure it is created with the proper Expires In param.
DbxRefreshResult expects Expires In Seconds, which is the time remaining for the token until expired.
However, we were passing in Expires At, which is the point in time where the token will be expired, in Millis.

The main idea is ExpiresIn seconds = (ExpiresAt millis - current time millis) / 1000

Modified the test cases to validate this logic and added an Offset because there is no way to inject the issued time.

### CODE REVIEW

File: src/main/java/com/dropbox/core/oauth/DbxRefreshResult.java [hunk 1]
```diff
@@ -19,8 +19,8 @@
  */
 public class DbxRefreshResult {
     private final String accessToken;
-    private final long expiresIn;
-    private long issueTime;
+    private final long expiresIn; /* in seconds */
+    private long issueTime; /* in milliseconds */
```
Comment (rallat) [inline src/main/java/com/dropbox/core/oauth/DbxRefreshResult.java:23]: I did not raname this fields to avoid adding extra noise in the review

File: src/main/java/com/dropbox/core/v2/DbxClientV2.java [hunk 2]
```diff
@@ -171,7 +171,7 @@ public DbxRefreshResult refreshAccessToken() throws DbxException {
         @Override
         public DbxRefreshResult refreshAccessToken() throws DbxException {
             credential.refresh(this.getRequestConfig());
-            return new DbxRefreshResult(credential.getAccessToken(), credential.getExpiresAt());
+            return new DbxRefreshResult(credential.getAccessToken(), (credential.getExpiresAt() - System.currentTimeMillis())/1000);
```
Comment (rallat) [inline src/main/java/com/dropbox/core/v2/DbxClientV2.java:174]: DbxRefreshResult expects "expires in" in seconds that means `(ExpiresAt (Millis) - currentMillis)/1000`

File: src/test/java/com/dropbox/core/oauth/DbxRefreshTest.java [hunk 3]
```diff
@@ -27,15 +27,16 @@
...
     private static final DbxRequestConfig CONFIG = DbxRequestConfig.newBuilder("DbxWebAuthTest/1.0")
         .withUserLocaleFrom(Locale.UK)
         .build();
     private static final DbxAppInfo APP = new DbxAppInfo("test-key", "test-secret");
     private static final String EXPIRED_TOKEN = "expired_token";
     private static final String REFRESH_TOKEN = "refresh____token";
     private static final String NEW_TOKEN = "new_token";
-    private static final long EXPIRES_IN = 14400;
+    private static final long EXPIRES_IN_SECONDS = 14400L;
+    private static final long OFFSET_BETWEEN_CALLS_IN_MS = 1000L;
```
Comment (rallat) [inline src/test/java/com/dropbox/core/oauth/DbxRefreshTest.java:39]: There is no way to inject the issuedTime into the client therefore I added an offset of 1 second.

File: src/test/java/com/dropbox/core/oauth/DbxRefreshTest.java [hunk 4]
```diff
@@ -27,15 +27,16 @@
...
+public class DbxRefreshTest extends DbxOAuthTestBase {
     private static final DbxRequestConfig CONFIG = DbxRequestConfig.newBuilder("DbxWebAuthTest/1.0")
         .withUserLocaleFrom(Locale.UK)
         .build();
     private static final DbxAppInfo APP = new DbxAppInfo("test-key", "test-secret");
     private static final String EXPIRED_TOKEN = "expired_token";
     private static final String REFRESH_TOKEN = "refresh____token";
     private static final String NEW_TOKEN = "new_token";
-    private static final long EXPIRES_IN = 14400;
+    private static final long EXPIRES_IN_SECONDS = 14400L;
```
Comment (rallat) [inline src/test/java/com/dropbox/core/oauth/DbxRefreshTest.java:38]: renamed this constant because it was getting confusing for testing

**Review by wclausen — APPROVED** [review]
