### PR TITLE
Fixes #456 and adds both login types to the sample app.

### LINKED ISSUE #456: Problem with oAuth2 flow in v5.4.0
I'm trying to update dependency from v5.3.0 to v5.4.0. But I'm getting runtime exception.
Namely
```
java.lang.IllegalStateException: Extra Query Param should only be used in short live token flow.
                 	at com.dropbox.core.android.internal.QueryParamsUtil.createExtraQueryParams$dropbox_sdk_java(QueryParamsUtil.kt:16)
                 	at com.dropbox.core.android.AuthActivity.onTopResumedActivityChanged(AuthActivity.kt:122)
                 	at android.app.Activity.performTopResumedActivityChanged(Activity.java:1973)
                 	at android.app.ActivityThread.reportTopResumedActivityChanged(ActivityThread.java:4633)
                 	at android.app.ActivityThread.handleTopResumedActivityChanged(ActivityThread.java:4617)
                 	at android.app.servertransaction.TopResumedActivityChangeItem.execute(TopResumedActivityChangeItem.java:39)
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loop(Looper.java:223)
                 	at android.app.ActivityThread.main(ActivityThread.java:7656)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
after starting auth proces with `Auth.startOAuth2Authentication(applicationContext, BuildConfig.DROPBOX_APP_KEY)`
Did a bit of digging and found that it's because `tokenAccessType` is passed as null to `QueryParamsUtil`. After following callstack I found that my `startOAuth2Authentication()` call ends up calling same function but with null as `tokenAccessType` (line 227 in Auth.kt file) so it sounds like a valid use case that seems to got broken during kotlin migration if you compare AuthActivity.onTopResumedActivityChanged between v5.3.0 with v5.4.0.

The big questions here are: 
- is it valid bug?
- am I doing something wrong? How it should be done then?

### PR DESCRIPTION
**Pull request by handstandsam**
This will fix #456 

Also adds an additional button to launch the normal `OAuth2` flow or the `OAuth2 PKCE` flow.
Screen Shot 2022-09-30 at 12 26 23 PM

### CODE REVIEW

File: dropbox-sdk-android/src/main/java/com/dropbox/core/android/internal/DropboxAuthIntent.kt [hunk 1]
```diff
@@ -32,7 +31,14 @@ internal object DropboxAuthIntent {
...
             putExtra(EXTRA_CALLING_PACKAGE, packageName)
             putExtra(EXTRA_AUTH_STATE, stateNonce)
+
             mState.mTokenAccessType?.apply {
+                val queryParams = QueryParamsUtil.createExtraQueryParams(
+                    tokenAccessType = mState.mTokenAccessType,
+                    scope = mState.mScope,
+                    includeGrantedScopes = mState.mIncludeGrantedScopes,
+                    pkceManagerCodeChallenge = mState.mPKCEManager.codeChallenge
+                )
```
Comment (handstandsam) [inline dropbox-sdk-android/src/main/java/com/dropbox/core/android/internal/DropboxAuthIntent.kt:41]: This is the actual fix.  The original java code make sure `mState.mTokenAccessType` was non-null.

File: dropbox-sdk-android/src/main/java/com/dropbox/core/android/AuthActivity.kt [hunk 2]
```diff
@@ -119,20 +117,12 @@ public open class AuthActivity : Activity() {
             createStateNonce(getSecurityProvider())
         }
 
-        val queryParams = QueryParamsUtil.createExtraQueryParams(
-            tokenAccessType = mState.mTokenAccessType,
-            scope = mState.mScope,
-            includeGrantedScopes = mState.mIncludeGrantedScopes,
-            pkceManagerCodeChallenge = mState.mPKCEManager.codeChallenge
-        )
-
```
Comment (handstandsam) [inline dropbox-sdk-android/src/main/java/com/dropbox/core/android/AuthActivity.kt:128]: This is where the crash started when `mState.mTokenAccessType` was `null`.  It worked fine on OAuth2 PKCE flows, but not standard OAuth2 Flows.

I've updated the sample app to support both types to ensure we are testing both flows regularly.
